const LP_ICONS = Object.freeze({
  // DeX Icons
  PGL: '/assets/images/lp-icons/PNG.png',
  JLP: '/assets/images/lp-icons/JOE.png',
  BLP: '/assets/images/lp-icons/BLP.png',
  TLP: '/assets/images/lp-icons/TLP.png',
  QLP: '/assets/images/lp-icons/BENQI.png',
  ALP: '/assets/images/lp-icons/AAVE.png',
  SNOB: '/assets/images/lp-icons/SNOWBALL.png',

  PNG: '/assets/images/lp-icons/PNG.png',
  WAVAX: '/assets/images/lp-icons/AVAX.png',
  ETHER: '/assets/images/lp-icons/ETH.png',
  ETH: '/assets/images/lp-icons/ETH.png',
  SHERPA: '/assets/images/lp-icons/SHERPA.png',
  LINK: '/assets/images/lp-icons/LINK.png',
  SUSHI: '/assets/images/lp-icons/SUSHI.png',
  WBTC: '/assets/images/lp-icons/WBTC.png',
  USDT: '/assets/images/lp-icons/USDT.png',
  DAI: '/assets/images/lp-icons/DAI.png',
  AAVE: '/assets/images/lp-icons/AAVE.png',
  UNI: '/assets/images/lp-icons/UNI.png',
  YFI: '/assets/images/lp-icons/YFI.png',
  FRAX: '/assets/images/lp-icons/FRAX.png',
  TUSD: '/assets/images/lp-icons/TUSD.png',
  BUSD: '/assets/images/lp-icons/BUSD.png',
  S3D: '/assets/images/lp-icons/S3D.png',
  S3F: '/assets/images/lp-icons/S3F.png',
  VSO: '/assets/images/lp-icons/VSO.png',
  SPORE: '/assets/images/lp-icons/SPORE.png',
  JOE: '/assets/images/lp-icons/JOE.png',
  QI: '/assets/images/lp-icons/BENQI.png',
  BENQI: '/assets/images/lp-icons/BENQI.png',
  'DAI.e': '/assets/images/lp-icons/DAI.png',
  'USDT.e': '/assets/images/lp-icons/USDT.png',
  'ETH.e': '/assets/images/lp-icons/ETH.png',
  'LINK.e': '/assets/images/lp-icons/LINK.png',
  'SUSHI.e': '/assets/images/lp-icons/SUSHI.png',
  'WBTC.e': '/assets/images/lp-icons/WBTC.png',
  'AAVE.e': '/assets/images/lp-icons/AAVE.png',
  'UNI.e': '/assets/images/lp-icons/AAVE.png',
  'YFI.e': '/assets/images/lp-icons/AAVE.png',
  NoIcon: '/assets/images/no-image.png'
})

export default LP_ICONS;