
import ANIMATIONS from 'utils/constants/animate-icons';

let Lotties = {};

Lotties[ANIMATIONS.WARNING.VALUE] = ANIMATIONS.WARNING.PATH
Lotties[ANIMATIONS.SUCCESS.VALUE] = ANIMATIONS.SUCCESS.PATH
Lotties[ANIMATIONS.ERROR.VALUE] = ANIMATIONS.ERROR.PATH


export default Lotties